### ISSUE TITLE
[Bug]: Forge Enhanced/Generic egg install script does not point to the unix_args.txt

### ISSUE THREAD

**Issue by LaiZBoi** [pelican-eggs/minecraft#21]
### Panel Version

1.0.0-beta6

### Wings Version

1.0.0-beta3

### Service

minecraft

### Modified

No, I did not modify the egg

### Expected Behavior

When I start the server, it should use the unix_args.txt file located in libraries/net/minecraftforge/forge/{forge version}/ and start.

### Actual Behavior

When you press start, it doesn't see the unix_args.txt and wants to use a server.jar when there is no server.jar for forge 1.18+ and the server will not start.

### Steps To Reproduce

Step 1: Create server using forge enhanced/generic egg.
Step 2: Let server install
Step 3: Start Server.

### Install logs

https://pastebin.com/AqD8pPV0

**Comment by spyderwan** [comment]
hey, for the fix it's pretty simple you go into the startup parameters and replace the Startup Command value with the one below Default Service Start Command and then save and you're all set. 

If you don't find what you're looking for, here's the value to put in Startup Command : java -Xms128M -Xmx{{SERVER_MEMORY}}M -Dterminal.jline=false -Dterminal.ansi=true $( [[  ! -f unix_args.txt ]] && printf %s "-jar {{SERVER_JARFILE}}" || printf %s "@unix_args.txt" )

**Comment by spyderwan** [comment]
hey, the command is given in the startup parameters under this line: **Default Service Start Command**
just set it under the **Startup Command line**

**here's the value to put in Startup Command :** 
`java -Xms128M -Xmx{{SERVER_MEMORY}}M -Dterminal.jline=false -Dterminal.ansi=true $( [[  ! -f unix_args.txt ]] && printf %s "-jar {{SERVER_JARFILE}}" || printf %s "@unix_args.txt" )`

**Comment by spyderwan** [comment]
message to those who update eggs: add this line to **docker_images**: `"Java 21": "ghcr.io/pterodactyl/yolks:java_21",`

**Comment by LaiZBoi** [comment]
You mean the startup like this? This is what it is currently set to.
![image](https://github.com/user-attachments/assets/53b79cee-f267-4b15-9793-ddfd509af90a)
And this is what it shows in console when I start the server.
![image](https://github.com/user-attachments/assets/d450a3bf-4e5f-4f74-9650-1cf2b8fd1756)
The only way to get the server running at this moment is to copy unix_args.txt into the root server folder where server.properties is located.

**Comment by spyderwan** [comment]
you have to put the start line in the red square on the picture
![unknown](https://github.com/user-attachments/assets/457e7edf-e0cc-4996-a40e-27c459c600c6)

Just to be sure, you've just put the installation on top of an existing one ? 
because when I try a new installation and just modify the startup line, I don't have any problems on my side

both files are created directly in the root folder : 
![unknown](https://github.com/user-attachments/assets/63d32183-ee5a-4e93-9723-fe55f840180d)

**Comment by LaiZBoi** [comment]
That is the startup command.
![image](https://github.com/user-attachments/assets/32f9304f-8473-4f90-9b5d-c15fa20ba5a9)
These are the egg settings.
![image](https://github.com/user-attachments/assets/93957bbd-d324-477d-8cc7-8801786db191)

I made a new server, with the egg and it booted up just fine. 
These are the files before startup
![image](https://github.com/user-attachments/assets/23e07117-4b19-4ab1-99c5-7466096f929c)

And these are the files after.
![image](https://github.com/user-attachments/assets/8555b3cb-24a7-458f-aea3-8709022f07ed)

There must of been something I either overlooked or something with the modpacks that are being used by my user. The modpack is using 1.18.2 Forge and Java 18. Would that cause the issues im seeing? Thanks for all the help.

**Comment by spyderwan** [comment]
I can't reproduce your error, but it could be due to the forge version used, as the recommended version uses java 18 while the lastest uses java 21. (forge 1.18.2)

Or just that the server installation itself was faulty, making it impossible just to force a Reinstall Server, and that creating a new installation fixed the problem.
