### ISSUE TITLE
[Install Bug]: egg-pterodactyl-modrinth-generic.json

### ISSUE THREAD

**Issue by Butain** [pelican-eggs/minecraft#30]
### Panel Version

1.11.7

### Wings Version

1.11.9

### Service

[egg-pterodactyl-modrinth-generic.json](https://github.com/pelican-eggs/minecraft/blob/main/java/modrinth/egg-pterodactyl-modrinth-generic.json)

### Modified

No, I did not modify the egg

### Expected Behavior

Install the server, using modrinth project id: 59ZceYlU server installs pixelmod mod and forge

### Actual Behavior

Server installs pixelmod modpack, does NOT appear to install forge, and says "Install completed succesfully, enjoy!"
At this point, there is no jar file and the server does not run when starting, owing to no jar file existing.

### Steps To Reproduce

Install the server, using modrinth project id: 59ZceYlU
then attempt to run the server (or locate the forge install.)

### Install logs

https://ptero.co/inayoveyaf

**Comment by Tober1276** [comment]
it seems like you're trying to install the [Pixelmon Mod](https://modrinth.com/mod/pixelmon) instead of the [Pixelmon Modpack](https://modrinth.com/modpack/the-pixelmon-modpack)

The Modrinth egg was designed so users can install modpacks and not individual mods hence why it's not installing forge.

Use Project ID `vwgtbO0y` for the Pixelmon Modpack
