### ISSUE TITLE
[Bug]: CurseForge : Unable to download Forge

### ISSUE THREAD

**Issue by oxygengamestudio** [pelican-eggs/minecraft#45]
### Panel Version

1.11.10

### Wings Version

1.11.13

### Service

Minecraft

### Modified

No, I did not modify the egg

### Expected Behavior

Install mod, install forge, then launch server 

### Actual Behavior

The server refuses to start because it cannot find the file server.jar

I analyzed the script and noticed that Forge's Maven repository now requires logins.

```
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from parkervcp/yolks 
Status: Image is up to date for ghcr.io/parkervcp/yolks:java_21 
Digest: sha256:68c64ff78e24f8a692b559dd29140fbe15d85397e980c894aba93c94ee0c96eb 
[Pterodactyl Daemon]: Finished pulling Docker container image
container@pelican~ java -version
openjdk version "21.0.5" 2024-10-15 LTS
OpenJDK Runtime Environment Temurin-21.0.5+11 (build 21.0.5+11-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.5+11 (build 21.0.5+11-LTS, mixed mode, sharing)
container@pelican~ java $([[ -f user_jvm_args.txt ]] && printf %s "@user_jvm_args.txt") -Xms128M -Xmx${SERVER_MEMORY}M -Dterminal.jline=false -Dterminal.ansi=true $([[ ! -f unix_args.txt ]] && printf %s "-jar `cat .serverjar`" || printf %s "@unix_args.txt")
cat: .serverjar: No such file or directory
Error: -jar requires jar file specification
```

### Steps To Reproduce

Installing the egg
Try to download All The Mods 10
And wait for error

### Install logs

I can't copy the link

**Comment by QuintenQVD0** [comment]
you will need to get us the install logs, else there is not that mutch that can be done.

**Comment by QuintenQVD0** [comment]
and this will not work because the how the devs did there modpack pack. Please see: https://www.youtube.com/watch?v=G_lAAzOO9c0

**Comment by QuintenQVD0** [comment]
> So if I understand correctly, there are a lot of mods that can't be downloaded like this?

Many work. Atm mods do not. And you still need an api key if you want it to try.

**Comment by LegitJaz** [comment]
I disagree that the issue is just that ATM10 changed the way they created their modpacks.
The [Pterodactyl CurseForge Generic Egg](https://github.com/pelican-eggs/minecraft/blob/main/java/curseforge/egg-pterodactyl-curse-forge-generic.json) can only download the Forge mod loader. 
This script ignores other mod loaders but the [Non Pterodactyl CurseForge Generic Egg](https://github.com/pelican-eggs/minecraft/blob/main/java/curseforge/egg-curse-forge-generic.json) allows for different mod loaders to be used.

The steps i took to resolve this issue is 

1. Go through the normal process to install the [Pterodactyl CurseForge Generic Egg](https://github.com/pelican-eggs/minecraft/blob/main/java/curseforge/egg-pterodactyl-curse-forge-generic.json)
2. After the installation failed with the .serverjar missing, I went to the bad CurseForge egg settings and went to the install script tab
3. I copied the install script from json of the  [Non Pterodactyl CurseForge Generic Egg](https://github.com/pelican-eggs/minecraft/blob/main/java/curseforge/egg-curse-forge-generic.json) into the Pterodactyl and had to manually change details in the script because of how the install script looks like in the JSON (it adds new lines and \'s to make sure the quote and slash translate properly to bash).
4. Then after going through issues with the SERVER_DIR variable(you need to change the SERVER_DIR to a proper variable Ex. 
SERVER_DIR="/mnt/server")
5. It worked, but only for Neoforge. I still have issues with Forge and potential other mod loaders that I am working through. I have looked into the issue, it has something to do with where the installed forge jar is and where it needs to be copied.

To make it easier you can use the [Non Pterodactyl CurseForge Generic Egg](https://github.com/pelican-eggs/minecraft/blob/main/java/curseforge/egg-curse-forge-generic.json) and change the beginning of the json from:
` "meta": {
        "version": "PTDL_v2",
        "update_url": null
    },
`
to
` "meta": {
        "version": "PLCN_v1",
        "update_url": null
    },
`

**Comment by SeritoCat** [comment]
I have the same problem and I don't really understand, I used different egg's but the error is the same everywhere....
how to solve the problems, or is it not possible to run forge builds on pelican?
